### ISSUE TITLE
Get Backgrounds and Sprites

### ISSUE THREAD

**Issue by ScarlandianProgrammer** [ScarlandianProgrammer/TheDataMines#11]
Receive and finalize the artwork for the game.

- [ ] Player sprite and animations
- [ ] NPC sprites and animations
- [ ] Item sprites
- [ ] Enemy sprites and animations
- [ ] Environment backgrounds
